# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
bioc_required: true

before_install:
- sudo apt-get update
- sudo apt-get install python3
  
addons:
  apt:
    packages:
    - python3-pip
      
before_install:
- sudo pip install --upgrade pip
  
script:
- R CMD build .

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual