# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: R
sudo: required
cache: packages
bioc_required: true

r:
  - oldrel
  - release
  - devel
  - bioc-release
  - bioc-devel
 
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install python3