# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r


language: R
sudo: required
cache: packages
bioc_required: true

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  
addons:
  apt:
    sources:
      - deadsnakes # source required so it finds the package definition below
    packages:
      - python3.5

r:
  - oldrel
  - release
  - devel
  - bioc-release
  - bioc-devel
  
os:
  - linux
  #- osx